stages:
  - build
  - test

image: gcc

default:
  tags:
    - common

build-job:
  stage: build
  before_script:
      - apt-get update
      - apt-get install -y git python3 clang cmake lcov libgtest-dev libsfml-dev libginac-dev
  script:
    - mkdir build && cd build && cmake .. && make 
  artifacts:
    expire_in: 7 days
    paths:
      - build
      - source
      - include
      - tests


unit-test-job: 
  stage: test
  before_script:
      - apt-get update
      - apt-get install -y git python3 clang cmake lcov libgtest-dev libsfml-dev libginac-dev
  script:
    - ./build/Test --gtest_output="xml:report.xml"
  artifacts:
    expire_in: 8 days
    paths:
      - report.xml
    reports:
      junit: report.xml

